# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(797, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.searchInputLine = QtWidgets.QLineEdit(self.centralwidget)
        self.searchInputLine.setGeometry(QtCore.QRect(20, 20, 361, 31))
        self.searchInputLine.setObjectName("searchInputLine")
        self.downloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.downloadButton.setGeometry(QtCore.QRect(610, 20, 151, 111))
        self.downloadButton.setObjectName("downloadButton")
        self.extensionComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.extensionComboBox.setGeometry(QtCore.QRect(480, 20, 81, 31))
        self.extensionComboBox.setEditable(True)
        self.extensionComboBox.setObjectName("extensionComboBox")
        self.countInputBox = QtWidgets.QSpinBox(self.centralwidget)
        self.countInputBox.setGeometry(QtCore.QRect(390, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.countInputBox.setFont(font)
        self.countInputBox.setMaximum(99999)
        self.countInputBox.setDisplayIntegerBase(10)
        self.countInputBox.setObjectName("countInputBox")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(390, 60, 171, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(120, 60, 171, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.maxSizeLbl = QtWidgets.QLabel(self.centralwidget)
        self.maxSizeLbl.setGeometry(QtCore.QRect(20, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.maxSizeLbl.setFont(font)
        self.maxSizeLbl.setObjectName("maxSizeLbl")
        self.minSizeLbl = QtWidgets.QLabel(self.centralwidget)
        self.minSizeLbl.setGeometry(QtCore.QRect(300, 60, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minSizeLbl.setFont(font)
        self.minSizeLbl.setObjectName("minSizeLbl")
        self.pathInputLine = QtWidgets.QLineEdit(self.centralwidget)
        self.pathInputLine.setGeometry(QtCore.QRect(120, 100, 361, 31))
        self.pathInputLine.setText("")
        self.pathInputLine.setObjectName("pathInputLine")
        self.downloadLabel = QtWidgets.QLabel(self.centralwidget)
        self.downloadLabel.setGeometry(QtCore.QRect(20, 100, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.downloadLabel.setFont(font)
        self.downloadLabel.setObjectName("downloadLabel")
        self.editPathcButton = QtWidgets.QPushButton(self.centralwidget)
        self.editPathcButton.setGeometry(QtCore.QRect(490, 100, 71, 31))
        self.editPathcButton.setObjectName("editPathcButton")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 140, 781, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.logInfoWidget = QtWidgets.QListWidget(self.centralwidget)
        self.logInfoWidget.setGeometry(QtCore.QRect(20, 170, 761, 411))
        self.logInfoWidget.setObjectName("logInfoWidget")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Images Downloader"))
        self.searchInputLine.setPlaceholderText(_translate("MainWindow", "What are you want to search?"))
        self.downloadButton.setText(_translate("MainWindow", "Download"))
        self.extensionComboBox.setCurrentText(_translate("MainWindow", "Extension"))
        self.countInputBox.setSpecialValueText(_translate("MainWindow", "Count"))
        self.maxSizeLbl.setText(_translate("MainWindow", "Max size (w  h)"))
        self.minSizeLbl.setText(_translate("MainWindow", "Min size (w  h)"))
        self.downloadLabel.setText(_translate("MainWindow", "Download to:"))
        self.editPathcButton.setText(_translate("MainWindow", "edit"))
